version: 2

jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: ~/
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Dependencies
          command: docker build -t puckel/docker-airflow .
  test:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: docker run puckel/docker-airflow version |grep '1.10.0'
